# Generated by Django 5.2.5 on 2025-08-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autores', '0002_alter_autor_name_alter_autor_nationality'),
        ('bibliotecas', '0004_alter_biblioteca_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Título')),
                ('year_of_publication', models.IntegerField(verbose_name='Año de publicación')),
                ('authors', models.ManyToManyField(to='autores.autor', verbose_name='Autor/es')),
                ('libraries', models.ManyToManyField(to='bibliotecas.biblioteca', verbose_name='Bibliotecas')),
            ],
        ),
    ]
