# Generated by Django 5.2.5 on 2025-08-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0004_alter_biblioteca_location'),
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='libraries',
            field=models.ManyToManyField(related_name='libros', to='bibliotecas.biblioteca', verbose_name='Bibliotecas'),
        ),
    ]
