# Generated by Django 5.2.5 on 2025-08-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_alter_libro_libraries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='title',
            field=models.CharField(max_length=70, unique=True, verbose_name='Título'),
        ),
    ]
