# Generated by Django 5.2.5 on 2025-08-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nationality',
            field=models.CharField(max_length=100, verbose_name='Nacionalidad'),
        ),
    ]
