# Generated by Django 5.2.5 on 2025-08-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('location', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ubicación')),
                ('type_biblioteca', models.CharField(choices=[('virtual', 'Virtual'), ('física', 'Fisíca')], default='virtual', max_length=10)),
            ],
            options={
                'verbose_name': 'Biblioteca',
                'verbose_name_plural': 'Bibliotecas',
            },
        ),
    ]
