# Generated by Django 5.2.5 on 2025-08-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0002_alter_biblioteca_type_biblioteca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='type_biblioteca',
            field=models.CharField(choices=[('virtual', 'virtual'), ('fisica', 'fisica')], default='virtual', max_length=10, verbose_name='tipo de biblioteca'),
        ),
    ]
