# Generated by Django 5.2.5 on 2025-08-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0003_alter_biblioteca_type_biblioteca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='location',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Ubicación'),
        ),
    ]
